### PR TITLE
ftpserver.c: Add sanity checks

### PR DESCRIPTION
**Pull request by robert-hh1**
- Line 354. Add "tls_mem_free(sbuf);" beforehand.
  sbuf is a local variable which is not retained between calls.
- Line 171. Add "ls_mem_free(sbuf);" beforehand.
  buffer is a local variable which is not retained between calls.
- function ftp_close_session(). That one seemed wrong, if the session
  to be closed is not the first one in the list. Besides that,
  the statements "session->next = NULL;" were obsolete,
  since the session object was anyhow free'd a few lines later.
- add checks after all tls_mem_alloc() calls for success/fail

### CODE REVIEW

**Comment by robert-hh** [comment]
Thanks for merging. But I will update ftpserver later. Last night. I found some more placed to improve. One of them caused corrupted file transfers.

**Comment by robert-hh1** [comment]
I'm not sure how to proceed git-wise. You can also  re-open that PR. Then I can add the change to this PR.
The open changes are:
- initialize session->offset to 0. That was not done, and when it had by bad luck values > 0, then downloads either failed or parts of the file were skipped. That happened more rarely than one could assume.
- if the name of session->currentdir ended in '/', the the resulting path name contains '//'. That did not cause trouble, so the fix is more cosmetic.
- and something REALLY cosmetic: Typos in messages, a user would normally not see.

So only the first change is important.

**Comment by wdyichen** [comment]
It seems that github does not have a reopen function, please mention a PR again

**Comment by robert-hh** [comment]
I issued a new PR

**Pull request merged**
